### PR TITLE
Upgrade to manifest v3, fix dropdown bug

### LINKED ISSUE #366: Skip type selection does not work
### Describe the bug

Selecting the skip type via the dropdown in the submit menu does not work with the mouse. Selecting the skip type using the keyboard works. 

### To Reproduce

1. Open the submit menu.
2. Change the skip type using the mouse.
3. It does not change.

### Device Information

1. Extension version: 1.8.7
2. Browser:
   1. Type: Chrome
   2. Version: 101.0.4951.67
3. Operating system:
   1. Type: -
   2. Version: -

### Related

https://github.com/tailwindlabs/headlessui/discussions/874

### Screenshots

_No response_

### Code of Conduct

- [X] I agree to fill in the correct information

### PR DESCRIPTION
**Pull request by lexesjan**
## Purpose

- Chrome will be deprecating manifest v2. 
- The skip type dropdown does not work in the submit menu. Closes #366.

## Proposed Change

Upgrade to manifest v3 (for Chrome only as Firefox does not support it currently).

## Checklist

- [x] Upgrade to manifest v3.
- [x] Fix dropdown bug.

## Additional

Out of scope changes:

- [x] Add new 9Anime player domain.
- [x] Change skip time to use frames instead of seconds.

### CODE REVIEW

File: src/api/base-http-client/base-http-client.ts [hunk 1]
```diff
@@ -10,34 +12,39 @@ export abstract class BaseHttpClient implements HttpClient {
...
 
-  async request<T = any, D = any>(
-    { route, ...rest }: Config<T>,
+  async request<D = any>(
+    { route, params, ...rest }: Config,
     isCallingBackgroundScript: boolean = true
   ): Promise<Response<D>> {
     const url = `${this.baseUrl}${route}`;
+    const config = {
+      ...(params && {
```
Comment (dabreadman) [inline src/api/base-http-client/base-http-client.ts:21]: nit: hmm.. what's happening here :?

image

**Review by dabreadman — APPROVED** [review]

File: src/api/base-http-client/base-http-client.ts (hunk 1 above)
Comment (lexesjan) [reply src/api/base-http-client/base-http-client.ts:21]: It is optional spreading of the `searchParams` key if `params` exists. Maybe a ternary would've been easier to read?
